version: '3.8'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - over


  backend:
    image: misieq/weii_ai_aplikacja_glowna_backend:latest
    container_name: backend-container
    restart: unless-stopped
    volumes:
      - ./backend/BackendServer/:/app/
    environment:
      - DJANGO_SUPERUSER_PASSWORD=admin 
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - LC_TIME="pl_PL"
      - RUN_MEMCACHE=TRUE
      - USE_POSTGRES=TRUE
    command: sh -c '(./wait-for db:5432 -- ./db-ops.sh ) && memcached start -u memcached -d && (nohup python3 cpu_usage.py &) &&  python3 ./manage.py runserver 0.0.0.0:8000'
    ports: 
      - 8000:8000
    depends_on:
      - rabbitmq
    networks:
      - over


  frontend:
    image: misieq/weii_ai_aplikacja_glowna_frontend:latest
    container_name: frontend-container
    restart: unless-stopped
    environment:
      - LC_TIME="pl_PL"
    ports:
      - 8081:8080
    depends_on:
      - backend
    networks:
      - over


  rabbitmq:
    hostname: rabbit
    image: rabbitmq:3-management
    environment:
        - RABBITMQ_DEFAULT_USER=guest 
        - RABBITMQ_DEFAULT_PASS=guest
        - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
        - LC_TIME="pl_PL"
    ports:
        - "15672:15672"  
        - "5672:5672"
    networks:
      - over
    
  celery:
    image: misieq/weii_ai_aplikacja_glowna_backend:latest
    command: celery -A Exchange  worker -l info
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - LC_TIME="pl_PL"
      - USE_POSTGRES=TRUE
    volumes:
      - ./backend/BackendServer/:/app/
    depends_on:
      - frontend
    networks:
      - over     


  celery-beat:
    image: misieq/weii_ai_aplikacja_glowna_backend:latest
    command: celery -A Exchange  beat -l info
    volumes:
      - ./backend/BackendServer:/app/
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - USE_POSTGRES=TRUE
      - LC_TIME="pl_PL"
    depends_on:
      - frontend
    networks:
      - over

networks: 
  over:
    external: true 

volumes:
  pgdata:
