version: '3.4'
services:
  backend:
    build: 
      context: ./backend/
      network: host
    container_name: backend-container
    restart: unless-stopped
    environment:
      - DJANGO_SUPERUSER_PASSWORD=admin 
  # volumes: nwm jeszcze
    command: python3 ./manage.py runserver 0.0.0.0:8000
    ports: 
      - 8000:8000

  frontend:
    build: 
      context: ./frontend/
      network: host
    container_name: frontend-container
    restart: unless-stopped
    command: npm run serve
    ports:
      - 8081:8080
    depends_on:
      - backend